// Generates src/tests/float_cases.h -- the expected-value table for
// test_float.c -- using real C 'float' arithmetic, so the C4 implementation in
// include/c4_float.h is checked against hardware rather than against its own
// assumptions.
//
// This is a native build-time tool, not C4 code:
//   gcc -O2 -o genfloat src/tests/genfloat.c
//   ./genfloat > src/tests/float_cases.h
//
// Subnormal inputs and results are skipped: c4_float.h flushes them to zero,
// which is its one documented departure from IEEE-754.
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

static uint32_t bits(float f){ uint32_t u; memcpy(&u,&f,4); return u; }
static float    fromb(uint32_t u){ float f; memcpy(&f,&u,4); return f; }

static int subnormal(uint32_t u){ return ((u>>23)&0xFF)==0 && (u&0x7FFFFF)!=0; }

static float vals[] = {
	0.0f, -0.0f, 1.0f, -1.0f, 2.0f, 0.5f, -0.5f, 3.0f, 10.0f,
	0.1f, 1.5f, 3.14159265f, -2.718281828f, 1e6f, 1e-6f,
	123456.789f, 65536.0f, 1.0f/3.0f, -7.0f, 1e20f, 1e-20f,
	16777217.0f, 1e30f, -0.0078125f,
};
static int nvals = sizeof(vals)/sizeof(vals[0]);

int main(void){
	int i, j, n = 0;
	unsigned seed = 12345;

	printf("// GENERATED by genfloat.c -- do not edit by hand.\n");
	printf("// Expected values come from native C 'float' arithmetic.\n");
	printf("// Format per line: <op> <a> <b> <expected>, hex, op in a s m d i t\n\n");
	printf("static char *float_case_data () { return\n");

	for (i = 0; i < nvals; i++) {
		for (j = 0; j < nvals; j++) {
			float a = vals[i], b = vals[j];
			uint32_t ab = bits(a), bb = bits(b);
			uint32_t r;
			if (subnormal(ab) || subnormal(bb)) continue;

			r = bits(a + b);
			if (!subnormal(r)) { printf("\t\"a %x %x %x\\n\"\n", ab, bb, r); n++; }
			r = bits(a - b);
			if (!subnormal(r)) { printf("\t\"s %x %x %x\\n\"\n", ab, bb, r); n++; }
			r = bits(a * b);
			if (!subnormal(r)) { printf("\t\"m %x %x %x\\n\"\n", ab, bb, r); n++; }
			r = bits(a / b);
			if (!subnormal(r)) { printf("\t\"d %x %x %x\\n\"\n", ab, bb, r); n++; }
		}
	}

	// pseudo-random pairs for wider coverage
	for (i = 0; i < 250; i++) {
		uint32_t ua, ub, r;
		float a, b;
		do { seed = seed*1103515245u+12345u; ua = (seed>>3) ^ (seed<<11); }
		while (((ua>>23)&0xFF)==0xFF || subnormal(ua));
		do { seed = seed*1103515245u+12345u; ub = (seed>>3) ^ (seed<<11); }
		while (((ub>>23)&0xFF)==0xFF || subnormal(ub));
		a = fromb(ua); b = fromb(ub);
		r = bits(a+b); if (!subnormal(r)) { printf("\t\"a %x %x %x\\n\"\n", ua, ub, r); n++; }
		r = bits(a-b); if (!subnormal(r)) { printf("\t\"s %x %x %x\\n\"\n", ua, ub, r); n++; }
		r = bits(a*b); if (!subnormal(r)) { printf("\t\"m %x %x %x\\n\"\n", ua, ub, r); n++; }
		r = bits(a/b); if (!subnormal(r)) { printf("\t\"d %x %x %x\\n\"\n", ua, ub, r); n++; }
	}

	printf("\t\"\";\n}\n\n");

	// int <-> float
	printf("static char *float_conv_data () { return\n");
	{
		long ints[] = {0,1,-1,2,7,-7,10,255,256,1000,123456,-123456,
		               16777216L,16777217L,1000000000L,-1000000000L,
		               1234567890123L, -1234567890123L, 0x7FFFFFFFL, -0x7FFFFFFFL};
		int k, nints = sizeof(ints)/sizeof(ints[0]);
		for (k = 0; k < nints; k++) {
			printf("\t\"i %lx %x\\n\"\n", ints[k], bits((float)ints[k]));
		}
		for (k = 0; k < nvals; k++) {
			float f = vals[k];
			if (subnormal(bits(f))) continue;
			if (f > 9.0e18f || f < -9.0e18f) continue;   // outside long range
			printf("\t\"t %x %lx\\n\"\n", bits(f), (long)f);
		}
	}
	printf("\t\"\";\n}\n\n");

	fprintf(stderr, "generated %d arithmetic cases\n", n);
	return 0;
}
