;; generated by c4.c from hello.c
.TARGET 64bit ;; recompilation required for other targets (32, 64)
.ENTRY [code + 8]

;; 1: #include <stdio.h>
;; 2: 
;; 3: int main()
;; 4: {
;; 5:   printf("hello, world\\foo\n");
    ENT  0
    IMM  [data + 0]
    PSH 
    PRTF
    ADJ  1
;; 6:   return 0;
    IMM  0
    LEV 
;; 7: }
    LEV 

DATA hello, world\0a\00\00\00\00\00\00\00
