;; generated by c4.c from test.c
.TARGET 64bit ;; recompilation required for other targets (32, 64)
.ENTRY [code + 104]

;; 01: #include <stdio.h>
;; 02: 
;; 03: int add (int a, int b) { return a + b; }
    ENT  0
    LEA  3
    LI  
    PSH 
    LEA  2
    LI  
    ADD 
    LEV 
    LEV 
;; 04: 
;; 05: int main(int argc, char **argv)
;; 06: {
;; 07:   int i;
;; 08:   printf("Argument count: %ld\n", argc);
    ENT  1
    IMM  [data + 0]
    PSH 
    LEA  3
    LI  
    PSH 
    PRTF
    ADJ  2
;; 09:   printf("2 + 2: %ld\n", add(2, 2));
    IMM  [data + 24]
    PSH 
    IMM  2
    PSH 
    IMM  2
    PSH 
    JSR  [code + 8]
    ADJ  2
    PSH 
    PRTF
    ADJ  2
;; 10:   i = 0;
    LEA  -1
    PSH 
    IMM  0
    SI  
;; 11:   while(i < argc) {
    LEA  -1
    LI  
    PSH 
    LEA  3
    LI  
    LT  
    BZ   [code + 800]
;; 12:     printf("Argument %ld: ", i);
    IMM  [data + 40]
    PSH 
    LEA  -1
    LI  
    PSH 
    PRTF
    ADJ  2
;; 13:     printf("'%s'\n", argv[i++]);
    IMM  [data + 56]
    PSH 
    LEA  2
    LI  
    PSH 
    LEA  -1
    PSH 
    LI  
    PSH 
    IMM  1
    ADD 
    SI  
    PSH 
    IMM  1
    SUB 
    PSH 
    IMM  8
    MUL 
    ADD 
    LI  
    PSH 
    PRTF
    ADJ  2
;; 14:   }
;; 15:   return 0;
    JMP  [code + 384]
    IMM  0
    LEV 
;; 16: }
    LEV 
;; 17: 

DATA Argument count: %ld\0a\00\00\00\002 + 2: %ld\0a\00\00\00\00\00Argument %l
DATA d: \00\00'%s'\0a\00\00\00
