;; generated by c4.c from test.c
.TARGET 64bit ;; recompilation required for other targets (32, 64)
.ENTRY [code + 104]

;; 01: #include <stdio.h>
;; 02: 
;; 03: int add (int a, int b) { return a + b; }
    ENT  0
    LEA  3
    LI  
    PSH 
    LEA  2
    LI  
    ADD 
    LEV 
    LEV 
;; 04: 
;; 05: int main(int argc, char **argv)
;; 06: {
;; 07:   int i;
;; 08:   printf("Argument count: %ld\n", argc);
    ENT  1
    IMM  [data + 0]
    PSH 
    LEA  3
    LI  
    PSH 
    PRTF
    ADJ  2
;; 09:   printf("2 + 2: %ld\n", add(2, 2));
    IMM  [data + 24]
    PSH 
    IMM  2
    PSH 
    IMM  2
    PSH 
    JSR  [code + 8]
    ADJ  2
    PSH 
    PRTF
    ADJ  2
;; 10:   return 0;
    IMM  0
    LEV 
;; 11: }
    LEV 
;; 12: 

DATA Argument count: %ld\0a\00\00\00\002 + 2: %ld\0a\00\00\00\00\00
