//
// C4M.JS - C4M for JavaScript
// Rewritten from the ground up, except for the imported modules.
// 32bit only.
'use asm';

var util = require('util');
var printj = require('printj');
const { Mallocator } = require('./simplest/mallocator');
var c4fs = require('./simplest/fs');

const POOLSZ = 256 * 1024;
const MAXPOOLSZ = 32 * 1024 * 1024; // 32mb
// Configure codes
const CONF_CYCLE_INTERRUPT_INTERVAL = 0, CONF_CYCLE_INTERRUPT_HANDLER = 1,
      CONF_PRIVS = 2;
// Privelege mode
const PRIV_KERNEL = 0, PRIV_USER = 1;
// C4INFO state
const
	C4I_NONE = 0x0,  // No C4 info
	C4I_C4   = 0x1,  // Ultimately running under C4
	C4I_C4M  = 0x2,  // Running under c4m (directly or C4)
	C4I_C4P  = 0x4,  // Running under c4plus
	C4I_C4MJS= 0x8,  // Running under C4M.JS host
	C4I_HRT  = 0x10, // High resolution timer
	C4I_SIG  = 0x20, // Signals supported
	C4I_FLT  = 0x40; // Floating point instruction support
// Trap codes
const
	// Illegal opcode, allows custom opcodes to be implemented using
	// install_trap_handler()
	TRAP_ILLOP = 0,
	// Hard IRQ generated by c4m under some condition
	TRAP_HARD_IRQ = 1,
	// Soft IRQ generated by user code
	TRAP_SOFT_IRQ = 2,
	// A POSIX signal was received
	TRAP_SIGNAL = 3,
	// Invalid memory read or write
	TRAP_SEGV = 4,
	// Invalid opcode value (specifically with OPCD)
	TRAP_OPV = 5;
// TRAP_HARD_IRQ codes
const HIRQ_CYCLE = 0;  // Cycle, runs every X cycles

// Opcodes, for reference
const  LEA  =  0, IMM  =  1, JMP  =  2, JSR  =  3, JSRI =  4, JSRS =  5, BZ   =  6,
	   BNZ  =  7, ENT  =  8, ADJ  =  9, LEV  = 10, LI   = 11, LC   = 12, SI   = 13,
	   SC   = 14, PSH  = 15, JMPA = 16, TLEV = 17,
       OR   = 18, XOR  = 19, AND  = 20, EQ   = 21, NE   = 22, LT   = 23, GT   = 24,
	   LE   = 25, GE   = 26, SHL  = 27, SHR  = 28, ADD  = 29, SUB  = 30, MUL  = 31,
	   DIV  = 32, MOD  = 33,
       OPEN = 34, READ = 35, CLOS = 36, PRTF = 37, MALC = 38, RALC = 39, FREE = 40,
	   MSET = 41, MCMP = 42, MCPY = 43, STRC = 44, ITH  = 45, _OPC = 46, _BLT = 47,
	   _TRP = 48, OPCD = 49, _JMP = 50, _ADJ = 51, C4CF = 52, C4CY = 53, TIME = 54,
	   SIGH = 55, SIGI = 56, USLP = 57, INFO = 58, OPSL = 59, FLT  = 60,
	   EXIT = 61;

function C4VM (code, memory) {
	this.code = code;
	= memory;
	this.run = 1 >>> 0;
	this.cycle = 0 >>> 0;
	this.status = 0 >>> 0;
	this.cycle_interrupt_interval = 0 >>> 0;
	this.cycle_interrupt_handler  = 0 >>> 0;
	this.sp = this.bp = 0 >>> 0; // TODO
	this.pc = this.a  = 0 >>> 0;
	this.pending_signal = 0 >>> 0;
	this.signal_handlers = []; // TODO
	this.trap_handler = 0 >>> 0;
	this.debug = false;
}

C4VM.prototype.run_cycles = function(cycles) {
	cycles = cycles >>> 0;
	while (--cycles) {
		++this.cycle;

		// Allow cycle interrupt. Also returns after trapping so that the JS engine
		// doesn't get tied up running non-stop.
		if (this.cycle_interrupt_interval && !(this.cycle % this.cycle_interrupt_interval)) {
			// console.log("!trap_hard_irq");
			this.trap(TRAP_HARD_IRQ, HIRQ_CYCLE, this.cycle_interrupt_handler);
			return;
		} else if (this.pending_signal) {
			// console.log("!trap_signal");
			this.trap(TRAP_SIGNAL, this.pending_signal, this.signal_handlers[this.pending_signal]);
			return;
		}

		// Read instruction
		var i = Read32(this.pc++);
		// Early opcode override
		if (i == OPCD) {
			i = Read32(this.sp);
			if (i <= ADJ) {
				// console.log("OPCD fault");
				this.trap(TRAP_OPV, i, this.trap_handler);
				i = C4CY; // harmless op
			}
		}

		if (this.debug) {
			// console.log(opcode lookup)
		}

		// Main evaluator
		switch(i) {
			case LEA:
				this.a = this.bp + Read32(this.pc); this.pc += WordSize;
				break;
			case IMM:
				this.a = Read32(this.pc); this.pc += WordSize;
				break;
			case JMP:
				this.pc = Read32(this.pc);
				break;
			case JMPA:
				this.pc = a;
				break;
			case _JMP:
				this.pc = Read32(this.sp); this.sp += WordSize;
				break;
			case JSR:
				this.sp -= WordSize; Write32(this.sp, this.pc + WordSize);
				this.pc = Read32(this.pc);
				break;
			case JSRI:
				this.sp -= WordSize; Write32(this.sp, this.pc + WordSize);
				this.pc = Read32(Read32(this.pc));
				break;
			case JSRS:
				this.sp -= WordSize; Write32(this.sp, this.pc + WordSize);
				this.pc = Read32(this.bp + Read32(this.pc));
				break;
			case BZ:
				this.pc = a ? this.pc + WordSize : Read32(this.pc);
				break;
			case BNZ:
				this.pc = a ? Read32(this.pc) : this.pc + WordSize;
				break;
			case ENT:
				this.sp -= WordSize; Write32(this.pc, this.bp);
				this.bp = this.sp;
				this.sp -= Read32(this.pc); this.pc += WordSize;
				break;
		}
	}
};
